// components/bpmn-q-vue/src/App.vue
<script setup>
import QFlowModeler from './components/QFlowModeler.vue';
</script>

<template>
    <div style="display: flex; height: 100%">
        <div style="width: 15%;"></div>
        <hr/>
        <div style="display: flex; flex-direction: column; height: 100%; width: 85%; flex: 1">
            <h1 style="margin: 10px">Vue BPMN Modeler</h1>
            <div id="vue-button-container" style="display: flex; flex-shrink: 0; height: 60px; background-color: lightgrey">
                <button class="my-button">Dummy</button>
                <button class="my-button">Save</button>
                <button class="my-button">Load</button>
            </div>
            <QFlowModeler/>
            <div style="height: 80px; background-color: lightgrey"></div>
        </div>
    </div>
</template>

<style scoped>
    .my-button {
        font-size: 18px;
        width: 150px;
        margin: 10px;
    }
</style>

// components/bpmn-q-angular/src/app/app.component.ts
import {Component, ViewEncapsulation} from '@angular/core';
// import '@planqk/quantum-workflow-modeler/public/app.js';
import '../../../bpmn-q/public/';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  encapsulation: ViewEncapsulation.None,
})
export class AppComponent {
  title = 'bpmn-q-angular';
}

<div style="display: flex; height: 100%">
  <div style="display: flex; flex-direction: column; height: 100%; width: 85%; flex: 1">
    <h1 style="margin: 10px">Angular BPMN Modeler</h1>
    <div id="angular-button-container" style="display: flex; flex-shrink: 0; height: 60px; background-color: lightgrey">
      <button class="my-button">Dummy</button>
      <button class="my-button">Save</button>
      <button class="my-button">Load</button>
    </div>
    <div style="height: 78vh; min-height: 85%">
      <quantum-workflow-modeler style="height: 100%; width: 100%" name="Lorem ipsum"></quantum-workflow-modeler>
    </div>
    <div style="height: 80px; background-color: lightgrey"></div>
  </div>
  <hr/>
  <div style="background-color: lightgrey; width: 15%"></div>
</div>
